### ISSUE TITLE
mac

### ISSUE THREAD

**Issue by TrixterTheTux** [glua/gm_fshook#2]
hello thsi doesnt work on mac fix plz bad dev!!!!!!!!!

**Comment by meepen** [comment]
i am not rich sorry

**Comment by TrixterTheTux** [comment]
ok understandable, have a good day.

**Comment by notcake** [comment]
i have a mac

**Comment by meepen** [comment]
but do people even use mac for gmod 🤔

**Comment by Kefta** [comment]
DarkRP players
